#define STANDALONE_ETR
#include <string>
#include <iostream>
#include <vector>
#include "stddef.h"
#include <cxxabi.h>
#include "../inst/include/etr_bits/Core/Reflection.hpp"
#include "../inst/include/etr.hpp"
using namespace etr;

template<typename L, typename R> void compare(const L& l, const R& r) {
  const double TOL = 1e-6;

  if constexpr (requires { l.isNaN(); } && requires {r.isNaN(); }) {
    if (l.isNaN() && r.isNaN()) {
      ass<"both values are NaN">(true);
      return;
    } else if (l.isNaN() && !r.isNaN()) {
      ass<"both values should be NaN">(false);
      return;
    }
  }
  if (l.isNA() && r.isNA()) {
    ass<"both values are NaN">(true);
    return;
  } else if (l.isNA() && !r.isNA()){
    ass<"both values should be NA">(false);
    return;
  }
  Double diff = l - r;
  if (diff < 0.0) diff = -diff;
  ass<"Values dont match">(diff < TOL);

  if constexpr (IS<Decayed<L>, Dual> || IS<Decayed<L>, DualRef>) {
    Dual dl = l;
    Dual dr = r;
    if (dl.isNaNDot() && dr.isNaNDot()) {
      ass<"both derivatives are NaN">(true);
      return;
    } else if (dl.isNaNDot() && !dr.isNaNDot()) {
      ass<"both derivatives should be NaN">(false);
      return;
    }
    if (dl.isNADot() && dr.isNADot()) {
      ass<"both derivatives are NA">(true);
      return;
    } else if (dl.isNADot() && !dr.isNADot()) {
      ass<"both derivatives should be NA">(false);
      return;
    }
    Double diff_dot;
    diff_dot.val = dl.dot - dr.dot;
    if (diff_dot < 0.0) diff_dot = -diff_dot;
    ass<"Derivatives dont match">(diff_dot < TOL);
  }
}

int main() {
  TAPE_INTERN.clear();

  Logical l1 = true;
  Logical l2 = Logical::NA();

  Integer i1 = 2;
  Integer i2 = Integer::NA();

  Double d1 = 3;
  Double d2 = Double::NA();
  Double d3 = Double::NaN();

  double d = 3.0;
  double d_dot = 4.0;
  Dual dua1(d, d_dot);
  Dual dua2(d, d_dot);
  dua2.is_na = true;
  dua2.is_na_dot = true;
  Dual dua3(d, d_dot);
  dua3.is_na = true;
  dua3.is_na_dot = false;
  Dual dua4(d, d_dot);
  dua4.is_na = false;
  dua4.is_na_dot = true;

  ReverseDouble revd1(5.0);
  ReverseDouble revd2 = d2;
  ReverseDouble revd3 = d3;

  bool lref_val1 = true;
  bool lref_na1 = false;
  LogicalRef lr_owned1(&lref_val1, &lref_na1);
  bool lref_val2 = true;
  bool lref_na2 = true;
  LogicalRef lr_owned2(&lref_val2, &lref_na2);

  int iref_val1 = 7;
  bool iref_na1 = false;
  IntegerRef ir_owned1(&iref_val1, &iref_na1);
  int iref_val2 = 7;
  bool iref_na2 = true;
  IntegerRef ir_owned2(&iref_val2, &iref_na2);

  double dref_val1 = 20.0;
  bool dref_na1 = false;
  DoubleRef dr_owned1(&dref_val1, &dref_na1);
  double dref_val2 = 20.0;
  bool dref_na2 = true;
  DoubleRef dr_owned2(&dref_val2, &dref_na2);

  double dualref_val1 = 2.0;
  double dualref_dot1 = 1.0;
  bool dualref_na1 = false;
  bool dualref_na_dot1 = false;
  DualRef duar_owned1(&dualref_val1, &dualref_dot1, &dualref_na1, &dualref_na_dot1);
  double dualref_val2 = 2.0;
  double dualref_dot2 = 1.0;
  bool dualref_na2 = true;
  bool dualref_na_dot2 = true;
  DualRef duar_owned2(&dualref_val2, &dualref_dot2, &dualref_na2, &dualref_na_dot2);
  double dualref_val3 = 3.0;
  double dualref_dot3 = 1.0;
  bool dualref_na3 = false;
  bool dualref_na_dot3 = true;
  DualRef duar_owned3(&dualref_val3, &dualref_dot3, &dualref_na3, &dualref_na_dot3);
  double dualref_val4 = 4.0;
  double dualref_dot4 = 1.0;
  bool dualref_na4 = true;
  bool dualref_na_dot4 = false;
  DualRef duar_owned4(&dualref_val4, &dualref_dot4, &dualref_na4, &dualref_na_dot4);

  double revdref_val1 = 9.0;
  uint8_t revdref_na1 = 0;
  ReverseDoubleRef revdr_owned1(&revdref_val1, &revdref_na1);
  double revdref_val2 = 9.0;
  uint8_t revdref_na2 = 1;
  ReverseDoubleRef revdr_owned2(&revdref_val2, &revdref_na2);
  compare(sin(l1), Double(0.841470984807897));
  compare(sin(l2), Logical::NA());
  compare(sin(i1), Double(0.909297426825682));
  compare(sin(i2), Integer::NA());
  compare(sin(d1), Double(0.141120008059867));
  compare(sin(d2), Double::NA());
  compare(sin(d3), Double::NaN());
  compare(sin(dua1), Dual(0.141120008059867, -0.989992496600445));
  compare(sin(dua2), Dual::NA());
  compare(sin(dua3), Dual::NA());
  compare(sin(dua4), Dual(0.141120008059867, std::numeric_limits<double>::quiet_NaN()));
  compare(sin(revd1), Double(-0.958924274663138));
  compare(sin(revd2), ReverseDouble::NA());
  compare(sin(revd3), ReverseDouble::NaN());
  compare(sin(lr_owned1), Double(0.841470984807897));
  compare(sin(lr_owned2), Logical::NA());
  compare(sin(ir_owned1), Double(0.656986598718789));
  compare(sin(ir_owned2), Integer::NA());
  compare(sin(dr_owned1), Double(0.912945250727628));
  compare(sin(dr_owned2), Double::NA());
  compare(sin(duar_owned1), Dual(0.909297426825682, -0.416146836547142));
  compare(sin(duar_owned2), Dual::NA());
  compare(sin(duar_owned3), Dual(0.141120008059867, std::numeric_limits<double>::quiet_NaN()));
  compare(sin(duar_owned4), Dual::NA());
  compare(sin(revdr_owned1), Double(0.412118485241757));
  compare(sin(revdr_owned2), ReverseDouble::NA());



compare(l1 * l1, Double(1));
 compare(l2 * l1, Double::NA());
 compare(i1 * l1, Double(2));
 compare(i2 * l1, Double::NA());
 compare(d1 * l1, Double(3));
 compare(d2 * l1, Double::NA());
 compare(d3 * l1, Double::NaN());

 compare(dua1 * l1, etr::Dual(3, 4));
 compare(dua2 * l1, Dual::NA());
 compare(dua3 * l1, Dual::NA());


 compare(dua4 * l1, Dual::NA());
  /*
 compare(revd1 * l1, Double(5));
 compare(revd2 * l1, Double::NA());
 compare(revd3 * l1, Double::NaN());
 compare(lr_owned1 * l1, Double(1));
 compare(lr_owned2 * l1, Double::NA());
 compare(ir_owned1 * l1, Double(7));
 compare(ir_owned2 * l1, Double::NA());
 compare(dr_owned1 * l1, Double(20));
 compare(dr_owned2 * l1, Double::NA());
 compare(duar_owned1 * l1, etr::Dual(2, 1));
 compare(duar_owned2 * l1, Dual::NA());
 compare(duar_owned3 * l1, Dual::NA());
 compare(duar_owned4 * l1, Dual::NA());
 compare(revdr_owned1 * l1, Double(9));
 compare(revdr_owned2 * l1, Double::NA());
 compare(l1 * l2, Double::NA());
 compare(l2 * l2, Double::NA());
 compare(i1 * l2, Double::NA());
 compare(i2 * l2, Double::NA());
 compare(d1 * l2, Double::NA());
 compare(d2 * l2, Double::NA());
 compare(d3 * l2, Double::NaN());
 compare(dua1 * l2, Dual::NA());
 compare(dua2 * l2, Dual::NA());
 compare(dua3 * l2, Dual::NA());
 compare(dua4 * l2, Dual::NA());
 compare(revd1 * l2, Double::NA());
 compare(revd2 * l2, Double::NA());
 compare(revd3 * l2, Double::NaN());
 compare(lr_owned1 * l2, Double::NA());
 compare(lr_owned2 * l2, Double::NA());
 compare(ir_owned1 * l2, Double::NA());
 compare(ir_owned2 * l2, Double::NA());
 compare(dr_owned1 * l2, Double::NA());
 compare(dr_owned2 * l2, Double::NA());
 compare(duar_owned1 * l2, Dual::NA());
 compare(duar_owned2 * l2, Dual::NA());
 compare(duar_owned3 * l2, Dual::NA());
 compare(duar_owned4 * l2, Dual::NA());
 compare(revdr_owned1 * l2, Double::NA());
 compare(revdr_owned2 * l2, Double::NA());
 compare(l1 * i1, Double(2));
 compare(l2 * i1, Double::NA());
 compare(i1 * i1, Double(4));
 compare(i2 * i1, Double::NA());
 compare(d1 * i1, Double(6));
 compare(d2 * i1, Double::NA());
 compare(d3 * i1, Double::NaN());
 compare(dua1 * i1, etr::Dual(6, 8));
 compare(dua2 * i1, Dual::NA());
 compare(dua3 * i1, Dual::NA());
 compare(dua4 * i1, Dual::NA());
 compare(revd1 * i1, Double(10));
 compare(revd2 * i1, Double::NA());
 compare(revd3 * i1, Double::NaN());
 compare(lr_owned1 * i1, Double(2));
 compare(lr_owned2 * i1, Double::NA());
 compare(ir_owned1 * i1, Double(14));
 compare(ir_owned2 * i1, Double::NA());
 compare(dr_owned1 * i1, Double(40));
 compare(dr_owned2 * i1, Double::NA());
 compare(duar_owned1 * i1, etr::Dual(4, 2));
 compare(duar_owned2 * i1, Dual::NA());
 compare(duar_owned3 * i1, Dual::NA());
 compare(duar_owned4 * i1, Dual::NA());
 compare(revdr_owned1 * i1, Double(18));
 compare(revdr_owned2 * i1, Double::NA());
 compare(l1 * i2, Double::NA());
 compare(l2 * i2, Double::NA());
 compare(i1 * i2, Double::NA());
 compare(i2 * i2, Double::NA());
 compare(d1 * i2, Double::NA());
 compare(d2 * i2, Double::NA());
 compare(d3 * i2, Double::NaN());
 compare(dua1 * i2, Dual::NA());
 compare(dua2 * i2, Dual::NA());
 compare(dua3 * i2, Dual::NA());
 compare(dua4 * i2, Dual::NA());
 compare(revd1 * i2, Double::NA());
 compare(revd2 * i2, Double::NA());
 compare(revd3 * i2, Double::NaN());
 compare(lr_owned1 * i2, Double::NA());
 compare(lr_owned2 * i2, Double::NA());
 compare(ir_owned1 * i2, Double::NA());
 compare(ir_owned2 * i2, Double::NA());
 compare(dr_owned1 * i2, Double::NA());
 compare(dr_owned2 * i2, Double::NA());
 compare(duar_owned1 * i2, Dual::NA());
 compare(duar_owned2 * i2, Dual::NA());
 compare(duar_owned3 * i2, Dual::NA());
 compare(duar_owned4 * i2, Dual::NA());
 compare(revdr_owned1 * i2, Double::NA());
 compare(revdr_owned2 * i2, Double::NA());
 compare(l1 * d1, Double(3));
 compare(l2 * d1, Double::NA());
 compare(i1 * d1, Double(6));
 compare(i2 * d1, Double::NA());
 compare(d1 * d1, Double(9));
 compare(d2 * d1, Double::NA());
 compare(d3 * d1, Double::NaN());
 compare(dua1 * d1, etr::Dual(9, 12));
 compare(dua2 * d1, Dual::NA());
 compare(dua3 * d1, Dual::NA());
 compare(dua4 * d1, Dual::NA());
 compare(revd1 * d1, Double(15));
 compare(revd2 * d1, Double::NA());
 compare(revd3 * d1, Double::NaN());
 compare(lr_owned1 * d1, Double(3));
 compare(lr_owned2 * d1, Double::NA());
 compare(ir_owned1 * d1, Double(21));
 compare(ir_owned2 * d1, Double::NA());
 compare(dr_owned1 * d1, Double(60));
 compare(dr_owned2 * d1, Double::NA());
 compare(duar_owned1 * d1, etr::Dual(6, 3));
 compare(duar_owned2 * d1, Dual::NA());
 compare(duar_owned3 * d1, Dual::NA());
 compare(duar_owned4 * d1, Dual::NA());
 compare(revdr_owned1 * d1, Double(27));
 compare(revdr_owned2 * d1, Double::NA());
 compare(l1 * d2, Double::NA());
 compare(l2 * d2, Double::NA());
 compare(i1 * d2, Double::NA());
 compare(i2 * d2, Double::NA());
 compare(d1 * d2, Double::NA());
 compare(d2 * d2, Double::NA());
 compare(d3 * d2, Double::NaN());
 compare(dua1 * d2, Dual::NA());
 compare(dua2 * d2, Dual::NA());
 compare(dua3 * d2, Dual::NA());
 compare(dua4 * d2, Dual::NA());
 compare(revd1 * d2, Double::NA());
 compare(revd2 * d2, Double::NA());
 compare(revd3 * d2, Double::NaN());
 compare(lr_owned1 * d2, Double::NA());
 compare(lr_owned2 * d2, Double::NA());
 compare(ir_owned1 * d2, Double::NA());
 compare(ir_owned2 * d2, Double::NA());
 compare(dr_owned1 * d2, Double::NA());
 compare(dr_owned2 * d2, Double::NA());
 compare(duar_owned1 * d2, Dual::NA());
 compare(duar_owned2 * d2, Dual::NA());
 compare(duar_owned3 * d2, Dual::NA());
 compare(duar_owned4 * d2, Dual::NA());
 compare(revdr_owned1 * d2, Double::NA());
 compare(revdr_owned2 * d2, Double::NA());
 compare(l1 * d3, Double::NaN());
 compare(l2 * d3, Double::NA());
 compare(i1 * d3, Double::NaN());
 compare(i2 * d3, Double::NA());
 compare(d1 * d3, Double::NaN());
 compare(d2 * d3, Double::NA());
 compare(d3 * d3, Double::NaN());
 compare(dua1 * d3, Dual::NA());
 compare(dua2 * d3, Dual::NA());
 compare(dua3 * d3, Dual::NA());
 compare(dua4 * d3, Dual::NA());
 compare(revd1 * d3, Double::NaN());
 compare(revd2 * d3, Double::NA());
 compare(revd3 * d3, Double::NaN());
 compare(lr_owned1 * d3, Double::NaN());
 compare(lr_owned2 * d3, Double::NA());
 compare(ir_owned1 * d3, Double::NaN());
 compare(ir_owned2 * d3, Double::NA());
 compare(dr_owned1 * d3, Double::NaN());
 compare(dr_owned2 * d3, Double::NA());
 compare(duar_owned1 * d3, Dual::NA());
 compare(duar_owned2 * d3, Dual::NA());
 compare(duar_owned3 * d3, Dual::NA());
 compare(duar_owned4 * d3, Dual::NA());
 compare(revdr_owned1 * d3, Double::NaN());
 compare(revdr_owned2 * d3, Double::NA());
 compare(l1 * dua1, etr::Dual(3, 4));
 compare(l2 * dua1, Dual::NA());
 compare(i1 * dua1, etr::Dual(6, 8));
 compare(i2 * dua1, Dual::NA());
 compare(d1 * dua1, etr::Dual(9, 12));
 compare(d2 * dua1, Dual::NA());
 compare(d3 * dua1, Dual::NA());
 compare(dua1 * dua1, etr::Dual(9, 24));
 compare(dua2 * dua1, Dual::NA());
 compare(dua3 * dua1, Dual::NA());
 compare(dua4 * dua1, Dual::NA());
 compare(revd1 * dua1, etr::Dual(15, 20));
 compare(revd2 * dua1, Dual::NA());
 compare(revd3 * dua1, Dual::NA());
 compare(lr_owned1 * dua1, etr::Dual(3, 4));
 compare(lr_owned2 * dua1, Dual::NA());
 compare(ir_owned1 * dua1, etr::Dual(21, 28));
 compare(ir_owned2 * dua1, Dual::NA());
 compare(dr_owned1 * dua1, etr::Dual(60, 80));
 compare(dr_owned2 * dua1, Dual::NA());
 compare(duar_owned1 * dua1, etr::Dual(6, 11));
 compare(duar_owned2 * dua1, Dual::NA());
 compare(duar_owned3 * dua1, Dual::NA());
 compare(duar_owned4 * dua1, Dual::NA());
 compare(revdr_owned1 * dua1, etr::Dual(27, 36));
 compare(revdr_owned2 * dua1, Dual::NA());
 compare(l1 * dua2, Dual::NA());
 compare(l2 * dua2, Dual::NA());
 compare(i1 * dua2, Dual::NA());
 compare(i2 * dua2, Dual::NA());
 compare(d1 * dua2, Dual::NA());
 compare(d2 * dua2, Dual::NA());
 compare(d3 * dua2, Dual::NA());
 compare(dua1 * dua2, Dual::NA());
 compare(dua2 * dua2, Dual::NA());
 compare(dua3 * dua2, Dual::NA());
 compare(dua4 * dua2, Dual::NA());
 compare(revd1 * dua2, Dual::NA());
 compare(revd2 * dua2, Dual::NA());
 compare(revd3 * dua2, Dual::NA());
 compare(lr_owned1 * dua2, Dual::NA());
 compare(lr_owned2 * dua2, Dual::NA());
 compare(ir_owned1 * dua2, Dual::NA());
 compare(ir_owned2 * dua2, Dual::NA());
 compare(dr_owned1 * dua2, Dual::NA());
 compare(dr_owned2 * dua2, Dual::NA());
 compare(duar_owned1 * dua2, Dual::NA());
 compare(duar_owned2 * dua2, Dual::NA());
 compare(duar_owned3 * dua2, Dual::NA());
 compare(duar_owned4 * dua2, Dual::NA());
 compare(revdr_owned1 * dua2, Dual::NA());
 compare(revdr_owned2 * dua2, Dual::NA());
 compare(l1 * dua3, Dual::NA());
 compare(l2 * dua3, Dual::NA());
 compare(i1 * dua3, Dual::NA());
 compare(i2 * dua3, Dual::NA());
 compare(d1 * dua3, Dual::NA());
 compare(d2 * dua3, Dual::NA());
 compare(d3 * dua3, Dual::NA());
 compare(dua1 * dua3, Dual::NA());
 compare(dua2 * dua3, Dual::NA());
 compare(dua3 * dua3, Dual::NA());
 compare(dua4 * dua3, Dual::NA());
 compare(revd1 * dua3, Dual::NA());
 compare(revd2 * dua3, Dual::NA());
 compare(revd3 * dua3, Dual::NA());
 compare(lr_owned1 * dua3, Dual::NA());
 compare(lr_owned2 * dua3, Dual::NA());
 compare(ir_owned1 * dua3, Dual::NA());
 compare(ir_owned2 * dua3, Dual::NA());
 compare(dr_owned1 * dua3, Dual::NA());
 compare(dr_owned2 * dua3, Dual::NA());
 compare(duar_owned1 * dua3, Dual::NA());
 compare(duar_owned2 * dua3, Dual::NA());
 compare(duar_owned3 * dua3, Dual::NA());
 compare(duar_owned4 * dua3, Dual::NA());
 compare(revdr_owned1 * dua3, Dual::NA());
 compare(revdr_owned2 * dua3, Dual::NA());
 compare(l1 * dua4, Dual::NA());
 compare(l2 * dua4, Dual::NA());
 compare(i1 * dua4, Dual::NA());
 compare(i2 * dua4, Dual::NA());
 compare(d1 * dua4, Dual::NA());
 compare(d2 * dua4, Dual::NA());
 compare(d3 * dua4, Dual::NA());
 compare(dua1 * dua4, Dual::NA());
 compare(dua2 * dua4, Dual::NA());
 compare(dua3 * dua4, Dual::NA());
 compare(dua4 * dua4, Dual::NA());
 compare(revd1 * dua4, Dual::NA());
 compare(revd2 * dua4, Dual::NA());
 compare(revd3 * dua4, Dual::NA());
 compare(lr_owned1 * dua4, Dual::NA());
 compare(lr_owned2 * dua4, Dual::NA());
 compare(ir_owned1 * dua4, Dual::NA());
 compare(ir_owned2 * dua4, Dual::NA());
 compare(dr_owned1 * dua4, Dual::NA());
 compare(dr_owned2 * dua4, Dual::NA());
 compare(duar_owned1 * dua4, Dual::NA());
 compare(duar_owned2 * dua4, Dual::NA());
 compare(duar_owned3 * dua4, Dual::NA());
 compare(duar_owned4 * dua4, Dual::NA());
 compare(revdr_owned1 * dua4, Dual::NA());
 compare(revdr_owned2 * dua4, Dual::NA());
 compare(l1 * revd1, Double(5));
 compare(l2 * revd1, Double::NA());
 compare(i1 * revd1, Double(10));
 compare(i2 * revd1, Double::NA());
 compare(d1 * revd1, Double(15));
 compare(d2 * revd1, Double::NA());
 compare(d3 * revd1, Double::NaN());
 compare(dua1 * revd1, etr::Dual(15, 20));
 compare(dua2 * revd1, Dual::NA());
 compare(dua3 * revd1, Dual::NA());
 compare(dua4 * revd1, Dual::NA());
 compare(revd1 * revd1, Double(25));
 compare(revd2 * revd1, Double::NA());
 compare(revd3 * revd1, Double::NaN());
 compare(lr_owned1 * revd1, Double(5));
 compare(lr_owned2 * revd1, Double::NA());
 compare(ir_owned1 * revd1, Double(35));
 compare(ir_owned2 * revd1, Double::NA());
 compare(dr_owned1 * revd1, Double(100));
 compare(dr_owned2 * revd1, Double::NA());
 compare(duar_owned1 * revd1, etr::Dual(10, 5));
 compare(duar_owned2 * revd1, Dual::NA());
 compare(duar_owned3 * revd1, Dual::NA());
 compare(duar_owned4 * revd1, Dual::NA());
 compare(revdr_owned1 * revd1, Double(45));
 compare(revdr_owned2 * revd1, Double::NA());
 compare(l1 * revd2, Double::NA());
 compare(l2 * revd2, Double::NA());
 compare(i1 * revd2, Double::NA());
 compare(i2 * revd2, Double::NA());
 compare(d1 * revd2, Double::NA());
 compare(d2 * revd2, Double::NA());
 compare(d3 * revd2, Double::NaN());
 compare(dua1 * revd2, Dual::NA());
 compare(dua2 * revd2, Dual::NA());
 compare(dua3 * revd2, Dual::NA());
 compare(dua4 * revd2, Dual::NA());
 compare(revd1 * revd2, Double::NA());
 compare(revd2 * revd2, Double::NA());
 compare(revd3 * revd2, Double::NaN());
 compare(lr_owned1 * revd2, Double::NA());
 compare(lr_owned2 * revd2, Double::NA());
 compare(ir_owned1 * revd2, Double::NA());
 compare(ir_owned2 * revd2, Double::NA());
 compare(dr_owned1 * revd2, Double::NA());
 compare(dr_owned2 * revd2, Double::NA());
 compare(duar_owned1 * revd2, Dual::NA());
 compare(duar_owned2 * revd2, Dual::NA());
 compare(duar_owned3 * revd2, Dual::NA());
 compare(duar_owned4 * revd2, Dual::NA());
 compare(revdr_owned1 * revd2, Double::NA());
 compare(revdr_owned2 * revd2, Double::NA());
 compare(l1 * revd3, Double::NaN());
 compare(l2 * revd3, Double::NA());
 compare(i1 * revd3, Double::NaN());
 compare(i2 * revd3, Double::NA());
 compare(d1 * revd3, Double::NaN());
 compare(d2 * revd3, Double::NA());
 compare(d3 * revd3, Double::NaN());
 compare(dua1 * revd3, Dual::NA());
 compare(dua2 * revd3, Dual::NA());
 compare(dua3 * revd3, Dual::NA());
 compare(dua4 * revd3, Dual::NA());
 compare(revd1 * revd3, Double::NaN());
 compare(revd2 * revd3, Double::NA());
 compare(revd3 * revd3, Double::NaN());
 compare(lr_owned1 * revd3, Double::NaN());
 compare(lr_owned2 * revd3, Double::NA());
 compare(ir_owned1 * revd3, Double::NaN());
 compare(ir_owned2 * revd3, Double::NA());
 compare(dr_owned1 * revd3, Double::NaN());
 compare(dr_owned2 * revd3, Double::NA());
 compare(duar_owned1 * revd3, Dual::NA());
 compare(duar_owned2 * revd3, Dual::NA());
 compare(duar_owned3 * revd3, Dual::NA());
 compare(duar_owned4 * revd3, Dual::NA());
 compare(revdr_owned1 * revd3, Double::NaN());
 compare(revdr_owned2 * revd3, Double::NA());
 compare(l1 * lr_owned1, Double(1));
 compare(l2 * lr_owned1, Double::NA());
 compare(i1 * lr_owned1, Double(2));
  */
}
