# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
  - mkdir -p ~/.R
  - echo 'CXX17 = -std=gnu++17 -fPIC' > ~/.R/Makevars


after_success:
  - Rscript -e 'covr::codecov()'
