# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev

script:
  - qmake
  - make
  - ./travis_clang_cpp17
