library(tinytest)
ast2ast:::test_basestore()
ast2ast:::test_vector_class()
ast2ast:::test_matrix_class()

ast2ast:::test_arithmetic_assign_to_buffer()
ast2ast:::test_arithmetic_assign_to_borrow()
ast2ast:::test_comparison()
ast2ast:::test_borrow()

ast2ast:::test_cmr()
ast2ast:::test_c()

ast2ast:::test_colon()
ast2ast:::test_concepts()
ast2ast:::test_isNA()
ast2ast:::test_isFinite()
ast2ast:::test_length()
ast2ast:::test_dim()

ast2ast:::test_matrices()

ast2ast:::test_rep()
ast2ast:::test_vector_subsetting()
ast2ast:::test_arithmetic_unary()
ast2ast:::test_numeric()
ast2ast:::test_int()
ast2ast:::test_bool()
ast2ast:::test_vector()
arg <- c(7, 8, 9)
ast2ast:::test_borrow_r(arg)
