library(tinytest)

ast2ast:::test_allocation()
ast2ast:::test_Borrow()
ast2ast:::test_buffer()
ast2ast:::test_calculation()
ast2ast:::test_cmr()
ast2ast:::test_concepts()
ast2ast:::test_first_dispatch_layer()
ast2ast:::test_jacobian()
ast2ast:::test_preserved_subsetting()
ast2ast:::test_second_dispatch_layer()
ast2ast:::test_simplified_subsetting()
ast2ast:::test_utilities()
