library(tinytest)
ast2ast:::test_basestore()
print("Test1")
ast2ast:::test_vector_class()
print("Test2")
ast2ast:::test_matrix_class()
print("Test3")

ast2ast:::test_arithmetic_assign_to_buffer()
print("Test4")
ast2ast:::test_arithmetic_assign_to_borrow()
print("Test5")
ast2ast:::test_comparison()
print("Test6")
ast2ast:::test_borrow()
print("Test7")

ast2ast:::test_cmr()
print("Test8")
ast2ast:::test_c()
print("Test9")

ast2ast:::test_colon()
ast2ast:::test_concepts()
ast2ast:::test_isNA()
ast2ast:::test_isFinite()
ast2ast:::test_length()
ast2ast:::test_dim()

ast2ast:::test_matrices()

ast2ast:::test_rep()
ast2ast:::test_vector_subsetting()
ast2ast:::test_arithmetic_unary()
ast2ast:::test_numeric()
ast2ast:::test_int()
ast2ast:::test_bool()
ast2ast:::test_vector()
arg <- c(7, 8, 9)
ast2ast:::test_borrow_r(arg)
