library(tinytest)
library(ast2ast)

expect_equal(ast2ast:::determine_literal_type(1), "numeric")
expect_equal(ast2ast:::determine_literal_type(1.2), "numeric")
expect_equal(ast2ast:::determine_literal_type(1e10), "scientific")
expect_equal(ast2ast:::determine_literal_type(1L), "integer")
expect_equal(ast2ast:::determine_literal_type(TRUE), "logical")
expect_equal(ast2ast:::determine_literal_type(NA), "NA")
expect_equal(ast2ast:::determine_literal_type(NaN), "NaN")
expect_equal(ast2ast:::determine_literal_type(Inf), "Inf")

expect_equal(ast2ast:::t_literal("print", 1, "", "numeric"), "etr::Double(1.0)")
expect_equal(ast2ast:::t_literal("<-", 1, "", "numeric"), "etr::Double(1.0)")

expect_equal(ast2ast:::t_literal("<-", 1L, "", "integer"), "etr::Integer(1)")
expect_equal(ast2ast:::t_literal("print", 1L, "", "integer"), "etr::Integer(1)")
expect_equal(ast2ast:::t_literal("<-", 1, "", "integer"), "etr::Integer(1)")

expect_equal(ast2ast:::t_literal("<-", TRUE, "", "logical"), "etr::Logical(true)")
expect_equal(ast2ast:::t_literal("print", TRUE, "", "logical"), "etr::Logical(true)")
expect_equal(ast2ast:::t_literal("<-", T, "", "logical"), "etr::Logical(true)")
expect_equal(ast2ast:::t_literal("print", T, "", "logical"), "etr::Logical(true)")
expect_equal(ast2ast:::t_literal("<-", FALSE, "", "logical"), "etr::Logical(false)")
expect_equal(ast2ast:::t_literal("print", FALSE, "", "logical"), "etr::Logical(false)")
expect_equal(ast2ast:::t_literal("<-", F, "", "logical"), "etr::Logical(false)")
expect_equal(ast2ast:::t_literal("print", F, "", "logical"), "etr::Logical(false)")

expect_equal(ast2ast:::t_literal("<-", NA, "", "NA"), "etr::Double::NA()")
expect_equal(ast2ast:::t_literal("print", NA, "", "NA"), "etr::Double::NA()")
expect_equal(ast2ast:::t_literal("<-", NaN, "", "NaN"), "etr::Double::NaN()")
expect_equal(ast2ast:::t_literal("print", NaN, "", "NaN"), "etr::Double::NaN()")
expect_equal(ast2ast:::t_literal("<-", Inf, "", "Inf"), "etr::Double::Inf()")
expect_equal(ast2ast:::t_literal("print", Inf, "", "Inf"), "etr::Double::Inf()")
