#include <Rcpp.h>
#include "../inst/include/etr.hpp"
using namespace etr;

// Minimal hand-written stand-in for a DSL-generated new_type struct (SEXP
// constructor + to_SEXP()), so Collection<T> can be exercised directly
// without going through the R-level DSL.
struct TestPoint {
  Double x;
  Double y;
  TestPoint() = default;
  TestPoint(const TestPoint&) = default;
  TestPoint(TestPoint&&) noexcept = default;
  TestPoint& operator=(const TestPoint&) = default;
  TestPoint& operator=(TestPoint&&) noexcept = default;
  TestPoint(Double x_, Double y_) : x(x_), y(y_) {}
  explicit TestPoint(SEXP arg) :
    x(SEXP2Scalar<Double>(checked_elt(arg, 0, 2, "TestPoint"))),
    y(SEXP2Scalar<Double>(checked_elt(arg, 1, 2, "TestPoint"))) {}
  SEXP to_SEXP() const {
    SEXP res = PROTECT(Rf_allocVector(VECSXP, 2));
    SET_VECTOR_ELT(res, 0, Cast(x));
    SET_VECTOR_ELT(res, 1, Cast(y));
    SEXP names = PROTECT(Rf_allocVector(STRSXP, 2));
    SET_STRING_ELT(names, 0, Rf_mkChar("x"));
    SET_STRING_ELT(names, 1, Rf_mkChar("y"));
    Rf_setAttrib(res, R_NamesSymbol, names);
    Rf_setAttrib(res, R_ClassSymbol, Rf_mkString("TestPoint"));
    UNPROTECT(2);
    return res;
  }
};

// [[Rcpp::export]]
void test_collection() {
  static_assert(IsCollection<Collection<TestPoint>>, "Collection<TestPoint> should satisfy IsCollection");
  static_assert(!IsCollection<TestPoint>, "TestPoint itself should not satisfy IsCollection");
  static_assert(!IsCollection<Double>, "Double should not satisfy IsCollection");

  // default construction
  {
    Collection<TestPoint> c;
    ass<"default-constructed Collection is empty">(c.size() == 0);
  }

  // std::size_t construction
  {
    Collection<TestPoint> c(3);
    ass<"size_t construction: correct size">(c.size() == 3);
  }

  // scalar-like (Integer / Double) construction -- matches how DSL-generated
  // code calls the constructor for vector(mode = "Point", n)
  {
    Collection<TestPoint> c(Integer(4));
    ass<"Integer-constructed Collection: correct size">(c.size() == 4);
  }
  {
    Collection<TestPoint> c(Double(5.0));
    ass<"Double-constructed Collection: correct size">(c.size() == 5);
  }

  // operator[] read/write
  {
    Collection<TestPoint> c(2);
    c[0] = TestPoint(Double(1.0), Double(2.0));
    c[1] = TestPoint(Double(3.0), Double(4.0));
    ass<"operator[] read back x">(std::abs(get_val(c[0].x) - 1.0) < 1e-9);
    ass<"operator[] read back y">(std::abs(get_val(c[1].y) - 4.0) < 1e-9);
  }

  // collection_at with a raw C++ long (1-based) -- the pre-existing path
  {
    Collection<TestPoint> c(2);
    c[0] = TestPoint(Double(10.0), Double(20.0));
    c[1] = TestPoint(Double(30.0), Double(40.0));
    ass<"collection_at(long): first element">(std::abs(get_val(collection_at(c, 1L).x) - 10.0) < 1e-9);
    ass<"collection_at(long): second element">(std::abs(get_val(collection_at(c, 2L).y) - 40.0) < 1e-9);
  }

  // collection_at with a scalar-like index (etr::Integer) -- matches how
  // pts[[i]] is generated by the DSL
  {
    Collection<TestPoint> c(2);
    c[0] = TestPoint(Double(10.0), Double(20.0));
    c[1] = TestPoint(Double(30.0), Double(40.0));
    ass<"collection_at(Integer): first element">(std::abs(get_val(collection_at(c, Integer(1)).x) - 10.0) < 1e-9);
    ass<"collection_at(Integer): second element">(std::abs(get_val(collection_at(c, Integer(2)).y) - 40.0) < 1e-9);
    collection_at(c, Integer(1)).x = Double(99.0);
    ass<"collection_at(Integer): mutation is visible through operator[]">(std::abs(get_val(c[0].x) - 99.0) < 1e-9);
  }

  // out-of-range access throws (bounds-checked via std::vector::at())
  {
    Collection<TestPoint> c(2);
    bool caught = false;
    try {
      collection_at(c, 5L);
    } catch (const std::exception&) {
      caught = true;
    }
    ass<"out-of-range collection_at throws">(caught);
  }
  {
    Collection<TestPoint> c(2);
    bool caught = false;
    try {
      collection_at(c, 0L); // wraps to a huge size_t, caught by .at()
    } catch (const std::exception&) {
      caught = true;
    }
    ass<"index 0 (out of range) throws">(caught);
  }

  // length() free function
  {
    Collection<TestPoint> c(7);
    Integer n = length(c);
    ass<"length() matches size()">(get_val(n) == 7);
  }

  // to_SEXP() / SEXP round trip
  {
    Collection<TestPoint> c(2);
    c[0] = TestPoint(Double(1.5), Double(2.5));
    c[1] = TestPoint(Double(3.5), Double(4.5));
    SEXP s = PROTECT(c.to_SEXP());
    ass<"to_SEXP: is a list">(static_cast<bool>(Rf_isNewList(s)));
    ass<"to_SEXP: correct length">(Rf_xlength(s) == 2);
    SEXP elt0 = VECTOR_ELT(s, 0);
    SEXP cls = Rf_getAttrib(elt0, R_ClassSymbol);
    ass<"to_SEXP: element class">(std::strcmp(CHAR(STRING_ELT(cls, 0)), "TestPoint") == 0);
    ass<"to_SEXP: element x value">(std::abs(Rf_asReal(VECTOR_ELT(elt0, 0)) - 1.5) < 1e-9);

    Collection<TestPoint> c2(s);
    ass<"round trip: size preserved">(c2.size() == 2);
    ass<"round trip: x preserved">(std::abs(get_val(c2[1].x) - 3.5) < 1e-9);
    ass<"round trip: y preserved">(std::abs(get_val(c2[0].y) - 2.5) < 1e-9);
    UNPROTECT(1);
  }

  // range-based for (used by the DSL's for-loop codegen for collections)
  {
    Collection<TestPoint> c(3);
    c[0] = TestPoint(Double(1.0), Double(0.0));
    c[1] = TestPoint(Double(2.0), Double(0.0));
    c[2] = TestPoint(Double(3.0), Double(0.0));
    double total = 0.0;
    for (const auto& p : c) {
      total += get_val(p.x);
    }
    ass<"range-based for sums correctly">(std::abs(total - 6.0) < 1e-9);
  }
}
