#include "../inst/include/etr.hpp"
using namespace etr;
#include <cstring>

void test_scalar_operations_return_types() {
  static_assert(IS<decltype(sin(std::declval<Logical>())), Double>, "sin(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(sin(std::declval<Integer>())), Double>, "sin(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(sin(std::declval<Double>())), Double>, "sin(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(sin(std::declval<Dual>())), Dual>, "sin(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(asin(std::declval<Logical>())), Double>, "asin(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(asin(std::declval<Integer>())), Double>, "asin(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(asin(std::declval<Double>())), Double>, "asin(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(asin(std::declval<Dual>())), Dual>, "asin(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(sinh(std::declval<Logical>())), Double>, "sinh(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(sinh(std::declval<Integer>())), Double>, "sinh(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(sinh(std::declval<Double>())), Double>, "sinh(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(sinh(std::declval<Dual>())), Dual>, "sinh(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(cos(std::declval<Logical>())), Double>, "cos(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(cos(std::declval<Integer>())), Double>, "cos(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(cos(std::declval<Double>())), Double>, "cos(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(cos(std::declval<Dual>())), Dual>, "cos(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(acos(std::declval<Logical>())), Double>, "acos(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(acos(std::declval<Integer>())), Double>, "acos(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(acos(std::declval<Double>())), Double>, "acos(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(acos(std::declval<Dual>())), Dual>, "acos(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(cosh(std::declval<Logical>())), Double>, "cosh(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(cosh(std::declval<Integer>())), Double>, "cosh(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(cosh(std::declval<Double>())), Double>, "cosh(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(cosh(std::declval<Dual>())), Dual>, "cosh(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(tan(std::declval<Logical>())), Double>, "tan(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(tan(std::declval<Integer>())), Double>, "tan(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(tan(std::declval<Double>())), Double>, "tan(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(tan(std::declval<Dual>())), Dual>, "tan(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(atan(std::declval<Logical>())), Double>, "atan(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(atan(std::declval<Integer>())), Double>, "atan(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(atan(std::declval<Double>())), Double>, "atan(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(atan(std::declval<Dual>())), Dual>, "atan(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(tanh(std::declval<Logical>())), Double>, "tanh(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(tanh(std::declval<Integer>())), Double>, "tanh(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(tanh(std::declval<Double>())), Double>, "tanh(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(tanh(std::declval<Dual>())), Dual>, "tanh(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(exp(std::declval<Logical>())), Double>, "exp(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(exp(std::declval<Integer>())), Double>, "exp(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(exp(std::declval<Double>())), Double>, "exp(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(exp(std::declval<Dual>())), Dual>, "exp(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(log(std::declval<Logical>())), Double>, "log(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(log(std::declval<Integer>())), Double>, "log(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(log(std::declval<Double>())), Double>, "log(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(log(std::declval<Dual>())), Dual>, "log(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(sqrt(std::declval<Logical>())), Double>, "sqrt(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(sqrt(std::declval<Integer>())), Double>, "sqrt(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(sqrt(std::declval<Double>())), Double>, "sqrt(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(sqrt(std::declval<Dual>())), Dual>, "sqrt(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(-(std::declval<Logical>())), Integer>, "-(std::declval<Logical>()) -> Integer");
  static_assert(IS<decltype(-(std::declval<Integer>())), Integer>, "-(std::declval<Integer>()) -> Integer");
  static_assert(IS<decltype(-(std::declval<Double>())), Double>, "-(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(-(std::declval<Dual>())), Dual>, "-(std::declval<Dual>()) -> Dual");

  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Logical>()), Integer>, "std::declval<Logical>() + std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Logical>()), Integer>, "std::declval<Integer>() + std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Logical>()), Double>, "std::declval<Double>() + std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() + std::declval<Logical>()), Dual>, "std::declval<Dual>() + std::declval<Logical>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Integer>()), Integer>, "std::declval<Logical>() + std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Integer>()), Integer>, "std::declval<Integer>() + std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Integer>()), Double>, "std::declval<Double>() + std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() + std::declval<Integer>()), Dual>, "std::declval<Dual>() + std::declval<Integer>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Double>()), Double>, "std::declval<Logical>() + std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Double>()), Double>, "std::declval<Integer>() + std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Double>()), Double>, "std::declval<Double>() + std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() + std::declval<Double>()), Dual>, "std::declval<Dual>() + std::declval<Double>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Dual>()), Dual>, "std::declval<Logical>() + std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Dual>()), Dual>, "std::declval<Integer>() + std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Dual>()), Dual>, "std::declval<Double>() + std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Dual>() + std::declval<Dual>()), Dual>, "std::declval<Dual>() + std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Logical>()), Integer>, "std::declval<Logical>() - std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Logical>()), Integer>, "std::declval<Integer>() - std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Logical>()), Double>, "std::declval<Double>() - std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() - std::declval<Logical>()), Dual>, "std::declval<Dual>() - std::declval<Logical>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Integer>()), Integer>, "std::declval<Logical>() - std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Integer>()), Integer>, "std::declval<Integer>() - std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Integer>()), Double>, "std::declval<Double>() - std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() - std::declval<Integer>()), Dual>, "std::declval<Dual>() - std::declval<Integer>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Double>()), Double>, "std::declval<Logical>() - std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Double>()), Double>, "std::declval<Integer>() - std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Double>()), Double>, "std::declval<Double>() - std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() - std::declval<Double>()), Dual>, "std::declval<Dual>() - std::declval<Double>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Dual>()), Dual>, "std::declval<Logical>() - std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Dual>()), Dual>, "std::declval<Integer>() - std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Dual>()), Dual>, "std::declval<Double>() - std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Dual>() - std::declval<Dual>()), Dual>, "std::declval<Dual>() - std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Logical>()), Integer>, "std::declval<Logical>() * std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Logical>()), Integer>, "std::declval<Integer>() * std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Logical>()), Double>, "std::declval<Double>() * std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() * std::declval<Logical>()), Dual>, "std::declval<Dual>() * std::declval<Logical>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Integer>()), Integer>, "std::declval<Logical>() * std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Integer>()), Integer>, "std::declval<Integer>() * std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Integer>()), Double>, "std::declval<Double>() * std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() * std::declval<Integer>()), Dual>, "std::declval<Dual>() * std::declval<Integer>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Double>()), Double>, "std::declval<Logical>() * std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Double>()), Double>, "std::declval<Integer>() * std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Double>()), Double>, "std::declval<Double>() * std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() * std::declval<Double>()), Dual>, "std::declval<Dual>() * std::declval<Double>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Dual>()), Dual>, "std::declval<Logical>() * std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Dual>()), Dual>, "std::declval<Integer>() * std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Dual>()), Dual>, "std::declval<Double>() * std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Dual>() * std::declval<Dual>()), Dual>, "std::declval<Dual>() * std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Logical>()), Double>, "std::declval<Logical>() / std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Logical>()), Double>, "std::declval<Integer>() / std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Logical>()), Double>, "std::declval<Double>() / std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() / std::declval<Logical>()), Dual>, "std::declval<Dual>() / std::declval<Logical>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Integer>()), Double>, "std::declval<Logical>() / std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Integer>()), Double>, "std::declval<Integer>() / std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Integer>()), Double>, "std::declval<Double>() / std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() / std::declval<Integer>()), Dual>, "std::declval<Dual>() / std::declval<Integer>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Double>()), Double>, "std::declval<Logical>() / std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Double>()), Double>, "std::declval<Integer>() / std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Double>()), Double>, "std::declval<Double>() / std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Dual>() / std::declval<Double>()), Dual>, "std::declval<Dual>() / std::declval<Double>() -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Dual>()), Dual>, "std::declval<Logical>() / std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Dual>()), Dual>, "std::declval<Integer>() / std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Dual>()), Dual>, "std::declval<Double>() / std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(std::declval<Dual>() / std::declval<Dual>()), Dual>, "std::declval<Dual>() / std::declval<Dual>() -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Logical>())), Double>, "etr::pow(std::declval<Logical>(), std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Logical>())), Double>, "etr::pow(std::declval<Integer>(), std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Logical>())), Double>, "etr::pow(std::declval<Double>(), std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Dual>(), std::declval<Logical>())), Dual>, "etr::pow(std::declval<Dual>(), std::declval<Logical>()) -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Integer>())), Double>, "etr::pow(std::declval<Logical>(), std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Integer>())), Double>, "etr::pow(std::declval<Integer>(), std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Integer>())), Double>, "etr::pow(std::declval<Double>(), std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Dual>(), std::declval<Integer>())), Dual>, "etr::pow(std::declval<Dual>(), std::declval<Integer>()) -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Double>())), Double>, "etr::pow(std::declval<Logical>(), std::declval<Double>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Double>())), Double>, "etr::pow(std::declval<Integer>(), std::declval<Double>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Double>())), Double>, "etr::pow(std::declval<Double>(), std::declval<Double>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Dual>(), std::declval<Double>())), Dual>, "etr::pow(std::declval<Dual>(), std::declval<Double>()) -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Dual>())), Dual>, "etr::pow(std::declval<Logical>(), std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Dual>())), Dual>, "etr::pow(std::declval<Integer>(), std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Dual>())), Dual>, "etr::pow(std::declval<Double>(), std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(etr::pow( std::declval<Dual>(), std::declval<Dual>())), Dual>, "etr::pow(std::declval<Dual>(), std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Logical>()), Logical>, "std::declval<Logical>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Logical>()), Logical>, "std::declval<Integer>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Logical>()), Logical>, "std::declval<Double>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() == std::declval<Logical>()), Logical>, "std::declval<Dual>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Integer>()), Logical>, "std::declval<Logical>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Integer>()), Logical>, "std::declval<Integer>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Integer>()), Logical>, "std::declval<Double>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() == std::declval<Integer>()), Logical>, "std::declval<Dual>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Double>()), Logical>, "std::declval<Logical>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Double>()), Logical>, "std::declval<Integer>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Double>()), Logical>, "std::declval<Double>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() == std::declval<Double>()), Logical>, "std::declval<Dual>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Dual>()), Logical>, "std::declval<Logical>() == std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Dual>()), Logical>, "std::declval<Integer>() == std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Dual>()), Logical>, "std::declval<Double>() == std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() == std::declval<Dual>()), Logical>, "std::declval<Dual>() == std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Logical>()), Logical>, "std::declval<Logical>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Logical>()), Logical>, "std::declval<Integer>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Logical>()), Logical>, "std::declval<Double>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() < std::declval<Logical>()), Logical>, "std::declval<Dual>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Integer>()), Logical>, "std::declval<Logical>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Integer>()), Logical>, "std::declval<Integer>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Integer>()), Logical>, "std::declval<Double>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() < std::declval<Integer>()), Logical>, "std::declval<Dual>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Double>()), Logical>, "std::declval<Logical>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Double>()), Logical>, "std::declval<Integer>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Double>()), Logical>, "std::declval<Double>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() < std::declval<Double>()), Logical>, "std::declval<Dual>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Dual>()), Logical>, "std::declval<Logical>() < std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Dual>()), Logical>, "std::declval<Integer>() < std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Dual>()), Logical>, "std::declval<Double>() < std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() < std::declval<Dual>()), Logical>, "std::declval<Dual>() < std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Logical>()), Logical>, "std::declval<Logical>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Logical>()), Logical>, "std::declval<Integer>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Logical>()), Logical>, "std::declval<Double>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() <= std::declval<Logical>()), Logical>, "std::declval<Dual>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Integer>()), Logical>, "std::declval<Logical>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Integer>()), Logical>, "std::declval<Integer>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Integer>()), Logical>, "std::declval<Double>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() <= std::declval<Integer>()), Logical>, "std::declval<Dual>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Double>()), Logical>, "std::declval<Logical>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Double>()), Logical>, "std::declval<Integer>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Double>()), Logical>, "std::declval<Double>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() <= std::declval<Double>()), Logical>, "std::declval<Dual>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Dual>()), Logical>, "std::declval<Logical>() <= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Dual>()), Logical>, "std::declval<Integer>() <= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Dual>()), Logical>, "std::declval<Double>() <= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() <= std::declval<Dual>()), Logical>, "std::declval<Dual>() <= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Logical>()), Logical>, "std::declval<Logical>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Logical>()), Logical>, "std::declval<Integer>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Logical>()), Logical>, "std::declval<Double>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() > std::declval<Logical>()), Logical>, "std::declval<Dual>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Integer>()), Logical>, "std::declval<Logical>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Integer>()), Logical>, "std::declval<Integer>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Integer>()), Logical>, "std::declval<Double>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() > std::declval<Integer>()), Logical>, "std::declval<Dual>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Double>()), Logical>, "std::declval<Logical>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Double>()), Logical>, "std::declval<Integer>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Double>()), Logical>, "std::declval<Double>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() > std::declval<Double>()), Logical>, "std::declval<Dual>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Dual>()), Logical>, "std::declval<Logical>() > std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Dual>()), Logical>, "std::declval<Integer>() > std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Dual>()), Logical>, "std::declval<Double>() > std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() > std::declval<Dual>()), Logical>, "std::declval<Dual>() > std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Logical>()), Logical>, "std::declval<Logical>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Logical>()), Logical>, "std::declval<Integer>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Logical>()), Logical>, "std::declval<Double>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() >= std::declval<Logical>()), Logical>, "std::declval<Dual>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Integer>()), Logical>, "std::declval<Logical>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Integer>()), Logical>, "std::declval<Integer>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Integer>()), Logical>, "std::declval<Double>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() >= std::declval<Integer>()), Logical>, "std::declval<Dual>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Double>()), Logical>, "std::declval<Logical>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Double>()), Logical>, "std::declval<Integer>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Double>()), Logical>, "std::declval<Double>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() >= std::declval<Double>()), Logical>, "std::declval<Dual>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Dual>()), Logical>, "std::declval<Logical>() >= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Dual>()), Logical>, "std::declval<Integer>() >= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Dual>()), Logical>, "std::declval<Double>() >= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() >= std::declval<Dual>()), Logical>, "std::declval<Dual>() >= std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Logical>()), Logical>, "std::declval<Logical>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Logical>()), Logical>, "std::declval<Integer>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Logical>()), Logical>, "std::declval<Double>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() != std::declval<Logical>()), Logical>, "std::declval<Dual>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Integer>()), Logical>, "std::declval<Logical>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Integer>()), Logical>, "std::declval<Integer>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Integer>()), Logical>, "std::declval<Double>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() != std::declval<Integer>()), Logical>, "std::declval<Dual>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Double>()), Logical>, "std::declval<Logical>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Double>()), Logical>, "std::declval<Integer>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Double>()), Logical>, "std::declval<Double>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() != std::declval<Double>()), Logical>, "std::declval<Dual>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Dual>()), Logical>, "std::declval<Logical>() != std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Dual>()), Logical>, "std::declval<Integer>() != std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Dual>()), Logical>, "std::declval<Double>() != std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() != std::declval<Dual>()), Logical>, "std::declval<Dual>() != std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Logical>()), Logical>, "std::declval<Logical>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Logical>()), Logical>, "std::declval<Integer>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Logical>()), Logical>, "std::declval<Double>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() && std::declval<Logical>()), Logical>, "std::declval<Dual>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Integer>()), Logical>, "std::declval<Logical>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Integer>()), Logical>, "std::declval<Integer>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Integer>()), Logical>, "std::declval<Double>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() && std::declval<Integer>()), Logical>, "std::declval<Dual>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Double>()), Logical>, "std::declval<Logical>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Double>()), Logical>, "std::declval<Integer>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Double>()), Logical>, "std::declval<Double>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() && std::declval<Double>()), Logical>, "std::declval<Dual>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Dual>()), Logical>, "std::declval<Logical>() && std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Dual>()), Logical>, "std::declval<Integer>() && std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Dual>()), Logical>, "std::declval<Double>() && std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() && std::declval<Dual>()), Logical>, "std::declval<Dual>() && std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Logical>()), Logical>, "std::declval<Logical>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Logical>()), Logical>, "std::declval<Integer>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Logical>()), Logical>, "std::declval<Double>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() || std::declval<Logical>()), Logical>, "std::declval<Dual>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Integer>()), Logical>, "std::declval<Logical>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Integer>()), Logical>, "std::declval<Integer>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Integer>()), Logical>, "std::declval<Double>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() || std::declval<Integer>()), Logical>, "std::declval<Dual>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Double>()), Logical>, "std::declval<Logical>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Double>()), Logical>, "std::declval<Integer>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Double>()), Logical>, "std::declval<Double>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() || std::declval<Double>()), Logical>, "std::declval<Dual>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Dual>()), Logical>, "std::declval<Logical>() || std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Dual>()), Logical>, "std::declval<Integer>() || std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Dual>()), Logical>, "std::declval<Double>() || std::declval<Dual>() -> Logical");
  static_assert(IS<decltype(std::declval<Dual>() || std::declval<Dual>()), Logical>, "std::declval<Dual>() || std::declval<Dual>() -> Logical");
}

void test_common_type() {
  static_assert(IS<etr::common_type_t<decltype(false), decltype(true)>, Logical> , "bool, bool -> Logical");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(true)>, Integer> , "int, bool -> Integer");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(true)>, Double> , "double, bool -> Double");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(true)>, Logical> , "Logical, bool -> Logical");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(true)>, Integer> , "Integer, bool -> Integer");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(true)>, Double> , "Double, bool -> Double");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(true)>, Dual> , "Dual, bool -> Dual");

  static_assert(IS<etr::common_type_t<decltype(false), decltype(1)>,Integer> , "bool, int-> Integer");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(1)>, Integer> , "int, int-> Integer");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(1)>, Double> , "double, int-> Double");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(1)>, Integer> , "Logical, int-> Integer");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(1)>, Integer> , "Integer, int-> Integer");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(1)>, Double> , "Double, int-> Double");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(1)>, Dual> , "Dual, int-> Dual");

  static_assert(IS<etr::common_type_t<decltype(false), decltype(1.1)>, Double> , "bool,double-> Double");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(1.2)>, Double> , "int, double-> Double");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(1.2)>, Double> , "double, double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(1.2)>, Double> , "Logical, double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(1.2)>, Double> , "Integer, double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(1.2)>, Double> , "Double, double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(1.2)>, Dual> , "Dual, double-> Dual");

  static_assert(IS<etr::common_type_t<decltype(false), decltype(Logical(true))>, Logical> , "bool, Logical->Logical");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(Logical(true))>, Integer> , "int, Logical->Integer");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(Logical(true))>, Double> , "double, Logical-> Double");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(Logical(true))>, Logical> , "Logical, Logical-> Logical");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(Logical(true))>, Integer> , "Integer, Logical-> Integer");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(Logical(true))>, Double> , "Double, Logical-> Double");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(Logical(true))>, Dual> , "Dual, Logical-> Dual");

  static_assert(IS<etr::common_type_t<decltype(false), decltype(Integer(10))>, Integer> , "bool, Integer->Integer");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(Integer(10))>, Integer> , "int, Integer->Integer");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(Integer(10))>, Double> , "double, Integer-> Double");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(Integer(10))>, Integer> , "Logical, Integer-> Integer");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(Integer(10))>, Integer> , "Integer, Integer-> Integer");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(Integer(10))>, Double> , "Double, Integer-> Double");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(Integer(10))>, Dual> , "Dual, Integer-> Dual");

  static_assert(IS<etr::common_type_t<decltype(false), decltype(Double(10.23))>, Double> , "bool, Double-> Double");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(Double(10.23))>, Double> , "int, Double-> Double");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(Double(10.23))>, Double> , "double, Double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(Double(10.23))>, Double> , "Logical, Double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(Double(10.23))>, Double> , "Integer, Double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(Double(10.23))>, Double> , "Double, Double-> Double");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(Double(10.23))>, Dual> , "Dual, Double-> Dual");

  static_assert(IS<etr::common_type_t<decltype(false), decltype(Dual(10.234, 0.0))>, Dual> , "bool, Dual-> Dual");
  static_assert(IS<etr::common_type_t<decltype(1), decltype(Dual(10.234, 0.0))>, Dual> , "int, Dual-> Dual");
  static_assert(IS<etr::common_type_t<decltype(1.23), decltype(Dual(10.234, 0.0))>, Dual> , "double, Dual-> Dual");
  static_assert(IS<etr::common_type_t<decltype(Logical(true)), decltype(Dual(10.234, 0.0))>, Dual> , "Logical, Dual-> Dual");
  static_assert(IS<etr::common_type_t<decltype(Integer(1)), decltype(Dual(10.234, 0.0))>, Dual> , "Integer, Dual-> Dual");
  static_assert(IS<etr::common_type_t<decltype(Double(1.1)), decltype(Dual(10.234, 0.0))>, Dual> , "Double, Dual-> Dual");
  static_assert(IS<etr::common_type_t<decltype(Dual(1.1, 0.0)), decltype(Dual(10.234, 0.0))>, Dual> , "Dual, Double-> Dual");
}

void test_reverse_ad() {
  static_assert(IS<decltype(sin(std::declval<Logical>())), Double>, "sin(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(sin(std::declval<Integer>())), Double>, "sin(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(sin(std::declval<Double>())), Double>, "sin(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(sin(std::declval<Dual>())), Dual>, "sin(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(sin(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "sin(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(asin(std::declval<Logical>())), Double>, "asin(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(asin(std::declval<Integer>())), Double>, "asin(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(asin(std::declval<Double>())), Double>, "asin(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(asin(std::declval<Dual>())), Dual>, "asin(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(asin(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "asin(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(sinh(std::declval<Logical>())), Double>, "sinh(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(sinh(std::declval<Integer>())), Double>, "sinh(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(sinh(std::declval<Double>())), Double>, "sinh(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(sinh(std::declval<Dual>())), Dual>, "sinh(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(sinh(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "sinh(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(cos(std::declval<Logical>())), Double>, "cos(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(cos(std::declval<Integer>())), Double>, "cos(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(cos(std::declval<Double>())), Double>, "cos(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(cos(std::declval<Dual>())), Dual>, "cos(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(cos(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "cos(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(acos(std::declval<Logical>())), Double>, "acos(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(acos(std::declval<Integer>())), Double>, "acos(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(acos(std::declval<Double>())), Double>, "acos(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(acos(std::declval<Dual>())), Dual>, "acos(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(acos(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "acos(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(cosh(std::declval<Logical>())), Double>, "cosh(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(cosh(std::declval<Integer>())), Double>, "cosh(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(cosh(std::declval<Double>())), Double>, "cosh(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(cosh(std::declval<Dual>())), Dual>, "cosh(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(cosh(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "cosh(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(tan(std::declval<Logical>())), Double>, "tan(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(tan(std::declval<Integer>())), Double>, "tan(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(tan(std::declval<Double>())), Double>, "tan(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(tan(std::declval<Dual>())), Dual>, "tan(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(tan(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "tan(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(atan(std::declval<Logical>())), Double>, "atan(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(atan(std::declval<Integer>())), Double>, "atan(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(atan(std::declval<Double>())), Double>, "atan(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(atan(std::declval<Dual>())), Dual>, "atan(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(atan(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "atan(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(tanh(std::declval<Logical>())), Double>, "tanh(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(tanh(std::declval<Integer>())), Double>, "tanh(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(tanh(std::declval<Double>())), Double>, "tanh(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(tanh(std::declval<Dual>())), Dual>, "tanh(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(tanh(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "tanh(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(exp(std::declval<Logical>())), Double>, "exp(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(exp(std::declval<Integer>())), Double>, "exp(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(exp(std::declval<Double>())), Double>, "exp(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(exp(std::declval<Dual>())), Dual>, "exp(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(exp(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "exp(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(log(std::declval<Logical>())), Double>, "log(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(log(std::declval<Integer>())), Double>, "log(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(log(std::declval<Double>())), Double>, "log(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(log(std::declval<Dual>())), Dual>, "log(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(log(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "log(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(sqrt(std::declval<Logical>())), Double>, "sqrt(std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(sqrt(std::declval<Integer>())), Double>, "sqrt(std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(sqrt(std::declval<Double>())), Double>, "sqrt(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(sqrt(std::declval<Dual>())), Dual>, "sqrt(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(sqrt(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "sqrt(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(-(std::declval<Logical>())), Integer>, "-(std::declval<Logical>()) -> Integer");
  static_assert(IS<decltype(-(std::declval<Integer>())), Integer>, "-(std::declval<Integer>()) -> Integer");
  static_assert(IS<decltype(-(std::declval<Double>())), Double>, "-(std::declval<Double>()) -> Double");
  static_assert(IS<decltype(-(std::declval<Dual>())), Dual>, "-(std::declval<Dual>()) -> Dual");
  static_assert(IS<decltype(-(std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "-(std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");

  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Logical>()), Integer>, "std::declval<Logical>() + std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Logical>()), Integer>, "std::declval<Integer>() + std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Logical>()), Double>, "std::declval<Double>() + std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() + std::declval<Logical>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() + std::declval<Logical>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Integer>()), Integer>, "std::declval<Logical>() + std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Integer>()), Integer>, "std::declval<Integer>() + std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Integer>()), Double>, "std::declval<Double>() + std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() + std::declval<Integer>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() + std::declval<Integer>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Double>()), Double>, "std::declval<Logical>() + std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Double>()), Double>, "std::declval<Integer>() + std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Double>()), Double>, "std::declval<Double>() + std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() + std::declval<Double>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() + std::declval<Double>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() + std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Logical>() + std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Integer>() + std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Integer>() + std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Double>() + std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Double>() + std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Variable<Double>>() + std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() + std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Logical>()), Integer>, "std::declval<Logical>() - std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Logical>()), Integer>, "std::declval<Integer>() - std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Logical>()), Double>, "std::declval<Double>() - std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() - std::declval<Logical>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() - std::declval<Logical>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Integer>()), Integer>, "std::declval<Logical>() - std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Integer>()), Integer>, "std::declval<Integer>() - std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Integer>()), Double>, "std::declval<Double>() - std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() - std::declval<Integer>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() - std::declval<Integer>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Double>()), Double>, "std::declval<Logical>() - std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Double>()), Double>, "std::declval<Integer>() - std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Double>()), Double>, "std::declval<Double>() - std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() - std::declval<Double>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() - std::declval<Double>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() - std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Logical>() - std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Integer>() - std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Integer>() - std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Double>() - std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Double>() - std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Variable<Double>>() - std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() - std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Logical>()), Integer>, "std::declval<Logical>() * std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Logical>()), Integer>, "std::declval<Integer>() * std::declval<Logical>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Logical>()), Double>, "std::declval<Double>() * std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() * std::declval<Logical>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() * std::declval<Logical>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Integer>()), Integer>, "std::declval<Logical>() * std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Integer>()), Integer>, "std::declval<Integer>() * std::declval<Integer>() -> Integer");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Integer>()), Double>, "std::declval<Double>() * std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() * std::declval<Integer>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() * std::declval<Integer>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Double>()), Double>, "std::declval<Logical>() * std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Double>()), Double>, "std::declval<Integer>() * std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Double>()), Double>, "std::declval<Double>() * std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() * std::declval<Double>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() * std::declval<Double>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() * std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Logical>() * std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Integer>() * std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Integer>() * std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Double>() * std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Double>() * std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Variable<Double>>() * std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() * std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Logical>()), Double>, "std::declval<Logical>() / std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Logical>()), Double>, "std::declval<Integer>() / std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Logical>()), Double>, "std::declval<Double>() / std::declval<Logical>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() / std::declval<Logical>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() / std::declval<Logical>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Integer>()), Double>, "std::declval<Logical>() / std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Integer>()), Double>, "std::declval<Integer>() / std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Integer>()), Double>, "std::declval<Double>() / std::declval<Integer>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() / std::declval<Integer>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() / std::declval<Integer>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Double>()), Double>, "std::declval<Logical>() / std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Double>()), Double>, "std::declval<Integer>() / std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Double>()), Double>, "std::declval<Double>() / std::declval<Double>() -> Double");
  static_assert(IS<decltype(std::declval<Variable<Double>>() / std::declval<Double>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() / std::declval<Double>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() / std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Logical>() / std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Integer>() / std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Integer>() / std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Double>() / std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Double>() / std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Variable<Double>>() / std::declval<Variable<Double>>()), std::shared_ptr<Expr<Double>>>, "std::declval<Variable<Double>>() / std::declval<Variable<Double>>() -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Logical>())), Double>, "etr::pow(std::declval<Logical>(), std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Logical>())), Double>, "etr::pow(std::declval<Integer>(), std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Logical>())), Double>, "etr::pow(std::declval<Double>(), std::declval<Logical>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Variable<Double>>(), std::declval<Logical>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Variable<Double>>(), std::declval<Logical>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Integer>())), Double>, "etr::pow(std::declval<Logical>(), std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Integer>())), Double>, "etr::pow(std::declval<Integer>(), std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Integer>())), Double>, "etr::pow(std::declval<Double>(), std::declval<Integer>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Variable<Double>>(), std::declval<Integer>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Variable<Double>>(), std::declval<Integer>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Double>())), Double>, "etr::pow(std::declval<Logical>(), std::declval<Double>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Double>())), Double>, "etr::pow(std::declval<Integer>(), std::declval<Double>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Double>())), Double>, "etr::pow(std::declval<Double>(), std::declval<Double>()) -> Double");
  static_assert(IS<decltype(etr::pow( std::declval<Variable<Double>>(), std::declval<Double>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Variable<Double>>(), std::declval<Double>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Logical>(), std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Logical>(), std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Integer>(), std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Integer>(), std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Double>(), std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Double>(), std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(etr::pow( std::declval<Variable<Double>>(), std::declval<Variable<Double>>())), std::shared_ptr<Expr<Double>>>, "etr::pow(std::declval<Variable<Double>>(), std::declval<Variable<Double>>()) -> std::shared_ptr<Expr<Double>>");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Logical>()), Logical>, "std::declval<Logical>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Logical>()), Logical>, "std::declval<Integer>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Logical>()), Logical>, "std::declval<Double>() == std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() == std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() == std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Integer>()), Logical>, "std::declval<Logical>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Integer>()), Logical>, "std::declval<Integer>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Integer>()), Logical>, "std::declval<Double>() == std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() == std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() == std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Double>()), Logical>, "std::declval<Logical>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Double>()), Logical>, "std::declval<Integer>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Double>()), Logical>, "std::declval<Double>() == std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() == std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() == std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() == std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() == std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() == std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() == std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() == std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() == std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() == std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() == std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Logical>()), Logical>, "std::declval<Logical>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Logical>()), Logical>, "std::declval<Integer>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Logical>()), Logical>, "std::declval<Double>() < std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() < std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() < std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Integer>()), Logical>, "std::declval<Logical>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Integer>()), Logical>, "std::declval<Integer>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Integer>()), Logical>, "std::declval<Double>() < std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() < std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() < std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Double>()), Logical>, "std::declval<Logical>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Double>()), Logical>, "std::declval<Integer>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Double>()), Logical>, "std::declval<Double>() < std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() < std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() < std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() < std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() < std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() < std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() < std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() < std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() < std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() < std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() < std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Logical>()), Logical>, "std::declval<Logical>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Logical>()), Logical>, "std::declval<Integer>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Logical>()), Logical>, "std::declval<Double>() <= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() <= std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() <= std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Integer>()), Logical>, "std::declval<Logical>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Integer>()), Logical>, "std::declval<Integer>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Integer>()), Logical>, "std::declval<Double>() <= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() <= std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() <= std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Double>()), Logical>, "std::declval<Logical>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Double>()), Logical>, "std::declval<Integer>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Double>()), Logical>, "std::declval<Double>() <= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() <= std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() <= std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() <= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() <= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() <= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() <= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() <= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() <= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() <= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() <= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Logical>()), Logical>, "std::declval<Logical>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Logical>()), Logical>, "std::declval<Integer>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Logical>()), Logical>, "std::declval<Double>() > std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() > std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() > std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Integer>()), Logical>, "std::declval<Logical>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Integer>()), Logical>, "std::declval<Integer>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Integer>()), Logical>, "std::declval<Double>() > std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() > std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() > std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Double>()), Logical>, "std::declval<Logical>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Double>()), Logical>, "std::declval<Integer>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Double>()), Logical>, "std::declval<Double>() > std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() > std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() > std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() > std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() > std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() > std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() > std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() > std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() > std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() > std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() > std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Logical>()), Logical>, "std::declval<Logical>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Logical>()), Logical>, "std::declval<Integer>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Logical>()), Logical>, "std::declval<Double>() >= std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() >= std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() >= std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Integer>()), Logical>, "std::declval<Logical>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Integer>()), Logical>, "std::declval<Integer>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Integer>()), Logical>, "std::declval<Double>() >= std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() >= std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() >= std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Double>()), Logical>, "std::declval<Logical>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Double>()), Logical>, "std::declval<Integer>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Double>()), Logical>, "std::declval<Double>() >= std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() >= std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() >= std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() >= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() >= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() >= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() >= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() >= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() >= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() >= std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() >= std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Logical>()), Logical>, "std::declval<Logical>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Logical>()), Logical>, "std::declval<Integer>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Logical>()), Logical>, "std::declval<Double>() != std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() != std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() != std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Integer>()), Logical>, "std::declval<Logical>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Integer>()), Logical>, "std::declval<Integer>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Integer>()), Logical>, "std::declval<Double>() != std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() != std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() != std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Double>()), Logical>, "std::declval<Logical>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Double>()), Logical>, "std::declval<Integer>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Double>()), Logical>, "std::declval<Double>() != std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() != std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() != std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() != std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() != std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() != std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() != std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() != std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() != std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() != std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() != std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Logical>()), Logical>, "std::declval<Logical>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Logical>()), Logical>, "std::declval<Integer>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Logical>()), Logical>, "std::declval<Double>() && std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() && std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() && std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Integer>()), Logical>, "std::declval<Logical>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Integer>()), Logical>, "std::declval<Integer>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Integer>()), Logical>, "std::declval<Double>() && std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() && std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() && std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Double>()), Logical>, "std::declval<Logical>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Double>()), Logical>, "std::declval<Integer>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Double>()), Logical>, "std::declval<Double>() && std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() && std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() && std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() && std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() && std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() && std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() && std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() && std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() && std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() && std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() && std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Logical>()), Logical>, "std::declval<Logical>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Logical>()), Logical>, "std::declval<Integer>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Logical>()), Logical>, "std::declval<Double>() || std::declval<Logical>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() || std::declval<Logical>()), BooleanExpr>, "std::declval<Variable<Double>>() || std::declval<Logical>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Integer>()), Logical>, "std::declval<Logical>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Integer>()), Logical>, "std::declval<Integer>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Integer>()), Logical>, "std::declval<Double>() || std::declval<Integer>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() || std::declval<Integer>()), BooleanExpr>, "std::declval<Variable<Double>>() || std::declval<Integer>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Double>()), Logical>, "std::declval<Logical>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Double>()), Logical>, "std::declval<Integer>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Double>()), Logical>, "std::declval<Double>() || std::declval<Double>() -> Logical");
  static_assert(IS<decltype(std::declval<Variable<Double>>() || std::declval<Double>()), BooleanExpr>, "std::declval<Variable<Double>>() || std::declval<Double>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Logical>() || std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Logical>() || std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Integer>() || std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Integer>() || std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Double>() || std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Double>() || std::declval<Variable<Double>>() -> BooleanExpr");
  static_assert(IS<decltype(std::declval<Variable<Double>>() || std::declval<Variable<Double>>()), BooleanExpr>, "std::declval<Variable<Double>>() || std::declval<Variable<Double>>() -> BooleanExpr");
}

// [[Rcpp::export]]
void test_second_dispatch_layer() {
  test_scalar_operations_return_types();
  test_common_type();
  test_reverse_ad();
}
