# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tests_allocation <- function() {
    invisible(.Call(`_ast2ast_tests_allocation`))
}

test_allocation <- function() {
    invisible(.Call(`_ast2ast_test_allocation`))
}

test_Borrow <- function() {
    invisible(.Call(`_ast2ast_test_Borrow`))
}

test_buffer <- function() {
    invisible(.Call(`_ast2ast_test_buffer`))
}

test_cmr <- function() {
    invisible(.Call(`_ast2ast_test_cmr`))
}

test_calculation <- function() {
    invisible(.Call(`_ast2ast_test_calculation`))
}

test_concepts <- function() {
    invisible(.Call(`_ast2ast_test_concepts`))
}

test_first_dispatch_layer <- function() {
    invisible(.Call(`_ast2ast_test_first_dispatch_layer`))
}

test_jacobian <- function() {
    invisible(.Call(`_ast2ast_test_jacobian`))
}

test_preserved_subsetting <- function() {
    invisible(.Call(`_ast2ast_test_preserved_subsetting`))
}

test_second_dispatch_layer <- function() {
    invisible(.Call(`_ast2ast_test_second_dispatch_layer`))
}

test_simplified_subsetting <- function() {
    invisible(.Call(`_ast2ast_test_simplified_subsetting`))
}

test_utilities <- function() {
    invisible(.Call(`_ast2ast_test_utilities`))
}

test_assign_array_to_scalar <- function() {
    invisible(.Call(`_ast2ast_test_assign_array_to_scalar`))
}

