# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_assign <- function(code) {
    .Call(`_AstToAst_is_assign`, code)
}

stor_var <- function(code) {
    .Call(`_AstToAst_stor_var`, code)
}

find_var_at_rhs <- function(code) {
    .Call(`_AstToAst_find_var_at_rhs`, code)
}

replace_assign <- function(code) {
    .Call(`_AstToAst_replace_assign`, code)
}

is_fct <- function(code) {
    .Call(`_AstToAst_is_fct`, code)
}

