# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getXPtrBorrowTest <- function() {
  .Call(`_ast2ast_getXPtrBorrowTest`)
}

callTestBorrow <- function(inp, a_, b, mat = FALSE, nrow = 0L, ncol = 0L) {
  .Call(`_ast2ast_callTestBorrow`, inp, a_, b, mat, nrow, ncol)
}
